import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "../components/NavBar";
import ParallaxProviders from "../components/ParallaxProviders";
import NextTopLoader from "nextjs-toploader";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "ZData Innovations",
  description: "Generated by Zdai",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Top loading bar */}
        <NextTopLoader
          color="#4D82C3"
          height={3}
          showSpinner={false}
          speed={200}
          easing="ease"
        />

        <ParallaxProviders>
          <NavBar />
          {children}
        </ParallaxProviders>
      </body>
    </html>
  );
}
