import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "../components/NavBar";
import ParallaxProviders from "../components/ParallaxProviders";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "Zdata1",
  description: "Generated by Zdai",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ParallaxProviders>
          <NavBar />
          {children}
        </ParallaxProviders>
      </body>
    </html>
  );
}
